services:
  mocker:
    image: dcreg.coinet.ge/mocker:beta
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Tbilisi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7006:8080"
