version: "3.4"
services:
  mocker:
    image: ${DOCKER_REGISTRY_COINET}/mocker
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Tbilisi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7006:8080"
